---
- hosts: localhost
  become: true
  tasks:
    - name: apt install
      ansible.builtin.apt:
        name:
          - lldpd
          - iperf3
          - apache2
          - vsftpd
          - tftpd
          - ufw
    
    - name: download script
      ansible.builtin.get_url:
        url: https://github.com/zawadzkis/ansible/edit/main/setup.sh
        dest: /root/setup.sh
    
    - name: run script
      ansible.builtin.shell:
        cmd: cmod u+x /root/setup.sh && bash /root/setup.sh 
