---
- hosts: localhost
  become: true
  tasks:
    - name: apt install
      ansible.builtin.apt:
        name:
          - lldpd
          - iperf3
          - apache2
          - vsftpd
          - tftpd
          - ufw
   
    - name: add user ansible
      ansible.builtin.shell: useradd ansible

    - name: enable ufw open port 22
      ansible.builtin.shell: ufw enable && ufw allow ssh
      
