---
- hosts: localhost
  become: true
  tasks:
    - name: apt install
      ansible.builtin.apt:
        name:
          - lldpd
          - iperf3
          - apache2
          - vsftpd
          - tftpd
          - ufw
   
    - name: add user ansible enable ufw allow ssh
      shell: ufw enable && ufw allow ssh
      
