---
- hosts: localhost
  become: true
  tasks:
    - name: apt install
      ansible.builtin.apt:
        name:
          - lldpd
          - iperf3
          - apache2
          - vsftpd
          - tftpd
          - ufw
   
    - name: add user ansible
      shell: useradd ansible
    
    - name: enable ufw open port 22
      shell: ufw enable && ufw allow ssh
      args:
        executable: /bin/bash
      
