---
- hosts: localhost
  become: true
  tasks:
    - name: apt install
      ansible.builtin.apt:
        name:
          - lldpd
          - iperf
          - apache2
          - vsftpd
          - tftpd
          - ufw
   
    - name: add user
      ansible.builtin.shell: useradd ansible
